spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.invilen.order.kafka.OrderConfirmation

server:
  port: 8070

application:
  config:
    customer-url: ${CUSTOMER_URL:http://localhost:8090/api/customers}
    bakery-url: ${BAKERY_URL:http://localhost:8050/api/bakery}
    pharmacy-url: ${PHARMACY_URL:http://localhost:8020/api/pharmacy}
